baseURL = 'https://www.stephenwuebker.com/'
languageCode = 'en-us'
title = 'Stephen Wuebker'
theme = 'mainroad' 

disqusShortname = '' # Enable Disqus comments by entering your Disqus shortname


[Permalinks]
  posts = "/:year/:month/:day/:filename"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 13
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'solarized-dark'
    tabWidth = 4

[Author] # Used in authorbox
  name = "Stephen Wuebker"
  bio = "I am a data professional and technologist living and working in Ohio. I am focused on working with the Microsoft stack, including SQL Server, PowerShell, Azure, etc. I also love to travel, cooking, craft beers and cocktails, and hanging out with our furkids."
  avatar = "/images/avatar.jpg"

[Params]
  description = "Stephen Wuebker's personal blog about life, the universe, everything" # Site description. Used in meta description
  copyright = "Stephen Wuebker" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  authorbox = true # Show authorbox at bottom of single pages if true
  comments = true # Enable comments for all site pages
  related = true # Enable Related content for single pages
  mathjax = false # Enable MathJax for all site pages
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path. Optional
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config. Optional
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  customCSS = ["/css/custom.css"] # Include custom CSS files

  [Params.logo]
  title = "stephenwuebker.com" # Logo title, otherwise will use site title
  subtitle = "Timely technology tidbits" # Logo subtitle

  [Params.thumbnail]
  visibility = "list" # Control thumbnail visibility

  [Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "taglist", "social", "languages"]


  [[Params.widgets.social.custom]]
  # Custom social links
  title = "Mastodon"
  url = "https://stephenwuebker.social/@stephen"
  icon = "svg/mastodon.svg" # Optional. Path relative to "layouts/partials"
  rel = "me"

  [Params.widgets.social]
  # Enable parts of social widget
  twitter = "stephenwuebker"
  linkedin = "stephen-wuebker"
  github = "stephenwuebker"
  email = "stephen@stephenwuebker.com"

  [Params.social.share]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = false
  email = true